export const SITE_TITLE = 'Seattle Birth Doulas'
export const BASE_URL = 'https://seattlebirthdoulas.com'
export const PHONE_NUMBER = '+12066576498'
export const PHONE_NUMBER_DISPLAY = '(206) 657-6498'
export const EMAIL = 'info@seattlebirthdoulas.com'

export const AMPLITUDE_API_KEY = 'e9453532d2f6f9b65172657496f60df2'

export const DOULA_TABLE_ID = 'tblceABbS6fBnuJA6'
export const POSTPARTUM_TABLE_ID = 'tbl4Jk6pGEogIZt8j'
export const PAGE_CONTENT_TABLE_ID = 'tblocAqWm54oz9Vo9'
export const HOW_WE_WORK_TABLE_ID = 'tblnyFjsIbQ3phvRN'
export const FAQ_TABLE_ID = 'tblrP50Bpp7WHjfhQ'
export const REVIEW_TABLE_ID = 'tblCjQPLzeLPMxcYi'

export const ABOUT_TABLE_ID = 'tbl00tSMeE16pYl4r'
export const VALUES_TABLE_ID = 'tblK1YEmIRi3um0SD'
export const SERVICES_TABLE_ID = 'tblsNcviLVDkMh3Ga'
export const TERMS_OF_SERVICE_TABLE_ID = 'tblak1tcWADwVT0d8'
export const PRIVACY_POLICY_TABLE_ID = 'tblKURV5bSHXLRBOn'
export const FOOTER_TABLE_ID = 'tblWSlovDOozf42mD'
